modules:
  http_2xx:
    prober: http
    timeout: 5s
    http:
      preferred_ip_protocol: "ip4"

  tcp_smtp_25:
    prober: tcp
    timeout: 5s
    tcp:
      preferred_ip_protocol: "ip4"

  tcp_submission_587:
    prober: tcp
    timeout: 5s
    tcp:
      preferred_ip_protocol: "ip4"

  tcp_imaps_993:
    prober: tcp
    timeout: 5s
    tcp:
      preferred_ip_protocol: "ip4"
