global:
  scrape_interval: 30s

scrape_configs:
  - job_name: "poste-blackbox-http"
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - https://host.docker.internal/
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: host.docker.internal:9115

  - job_name: "poste-blackbox-tcp"
    metrics_path: /probe
    static_configs:
      - targets:
          - host.docker.internal:25
          - host.docker.internal:587
          - host.docker.internal:993
    relabel_configs:
      - source_labels: [__address__]
        regex: ".*:25"
        target_label: __param_module
        replacement: tcp_smtp_25
      - source_labels: [__address__]
        regex: ".*:587"
        target_label: __param_module
        replacement: tcp_submission_587
      - source_labels: [__address__]
        regex: ".*:993"
        target_label: __param_module
        replacement: tcp_imaps_993
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: host.docker.internal:9115
