global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "gitea"
    metrics_path: /metrics
    static_configs:
      - targets: ["gitea:3000"]
    bearer_token_file: /run/secrets/gitea_metrics_token
