global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: kafka-jmx
    static_configs:
      - targets:
          - "kafka1:7071"
          - "kafka2:7072"
          - "kafka3:7073"

  - job_name: kafka-exporter
    static_configs:
      - targets: ["kafka-exporter:9308"]

  - job_name: akhq
    metrics_path: /prometheus
    static_configs:
      - targets: ["akhq:28081"]
