scrape_configs:
  - job_name: "beanstalkd"
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
      - targets:
          - beanstalkd_exporter:8080
        labels:
          service: "beanstalkd"
          component: "exporter"
