global:
  scrape_interval: 15s

scrape_configs:
  - job_name: nginx_exporter
    static_configs:
      - targets: ["nginx-exporter:9113"]

  - job_name: cert_exporter
    static_configs:
      - targets: ["cert-exporter:9219"]
