global:
  scrape_interval: 15s

scrape_configs:
  - job_name: keycloak
    metrics_path: /metrics
    static_configs:
      - targets: ["keycloak:9000"]

  - job_name: postgres
    static_configs:
      - targets: ["postgres_exporter:9187"]
