global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "registry-debug"
    metrics_path: /metrics
    static_configs:
      - targets: ["registry:5001"]

  - job_name: "registry-exporter"
    static_configs:
      - targets: ["registry-exporter:9100"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
