global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "redis"
    static_configs:
      - targets:
          - redis-exporter-1:9121
          - redis-exporter-2:9121
          - redis-exporter-3:9121
