[globals]
gluster-mgmt = "glusterd"
glusterd-dir = "/var/lib/glusterd"
gluster-binary-path = "gluster"

port = 9713
metrics-path = "/metrics"

log-dir = "/var/log"
log-file = "gluster-exporter.log"
log-level = "info"
