global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "postgres-primary"
    static_configs:
      - targets: ["postgres-exporter-primary:9187"]

  - job_name: "postgres-replica1"
    static_configs:
      - targets: ["postgres-exporter-replica1:9187"]
