global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "nginx_exporter"
    static_configs:
      - targets: ["nginx_exporter:9113"]

  # Optional: scrape Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
