global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "kafka-jmx"
    metrics_path: /metrics
    static_configs:
      - targets: ["kafka:9404"]

  - job_name: "kafka-exporter"
    metrics_path: /metrics
    static_configs:
      - targets: ["kafka-exporter:9308"]
