global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "laravel"
    metrics_path: /metrics
    static_configs:
      - targets: ["app:8000"]

  - job_name: "redis_exporter"
    static_configs:
      - targets: ["redis_exporter:9121"]
